//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.Tutorials = new HashSet<Tutorial>();
            this.UserSpecialities = new HashSet<UserSpeciality>();
        }
    
        public int SpecialityId { get; set; }
        public string SpecialityName { get; set; }
    
        public virtual ICollection<Tutorial> Tutorials { get; set; }
        public virtual ICollection<UserSpeciality> UserSpecialities { get; set; }
    }
}
