//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public Town()
        {
            this.Users = new HashSet<User>();
        }
    
        public int TownId { get; set; }
        public string TownName { get; set; }
        public int StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
