//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Infrastructures = new HashSet<Infrastructure>();
            this.Tutorials = new HashSet<Tutorial>();
            this.UserSpecialities = new HashSet<UserSpeciality>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Passwor { get; set; }
        public byte[] CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UserType { get; set; }
        public string SeoName { get; set; }
        public string TutorCenterName { get; set; }
        public string PhysicalAddress { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> TownId { get; set; }
        public string ProfileImageUrl { get; set; }
        public string Degree { get; set; }
        public string GpsCoordinates { get; set; }
        public string description { get; set; }
        public string Phone { get; set; }
        public Nullable<int> AvailablePersonel { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Infrastructure> Infrastructures { get; set; }
        public virtual State State { get; set; }
        public virtual Town Town { get; set; }
        public virtual ICollection<Tutorial> Tutorials { get; set; }
        public virtual ICollection<UserSpeciality> UserSpecialities { get; set; }
    }
}
